### PR TITLE
More Navigation Buttons

### PR DESCRIPTION
**Pull request by deklinez**
* Added First/Last buttons to go the First/Last card of current color
* Added Latest button to go to the latest populated card
* Modified default cube directory to app config setting

**Note**
* Can definitely be optimized but pushing it up for convenience

### CODE REVIEW

**Comment by LethargicDeveloper** [comment]
We already have quick keys to jump to the first card of the next color.
Did we want the nav buttons to match? Ie, jump to first card of next color rather than last card of current color.

Hitting the `Latest` button crashes the app.

**Comment by deklinez** [comment]
Hmm, once the back button works as expected that probably makes more sense as it's just 1 more click.

And that's odd, it works fine for me.  Are you getting an exception?

**Comment by LethargicDeveloper** [comment]
I probably should have given you more details, but I was in a hurry to go eat dinner :)

MainForm.cs line 913
`System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')'`

`Card GetCurrentCard() {
  var scryfallCard = this.scryfallCards[this.currentCard];
}
`

It's trying to access the current scryfall card, but the currentCard index is -1

Attached is the entire test cube that's causing the issue.

[cube.zip](https://github.com/LethargicDeveloper/hypercube/files/9536810/cube.zip)

**Comment by deklinez** [comment]
So I can't open the test cube you attached, I just get an `Error Loading Cube` message.  The latest commit should prevent a -1 assignment and fixed a bug where it would get confused in colors with no cards though.

And after thinking about it more are we sure the buttons should move to the first card of the next color instead of the last card of the current color?  In most lists `>/<` means "next/previous" and `>>/<<` mean "move to the first/last element".

**Comment by LethargicDeveloper** [comment]
The main reason I wanted it going to the next color was for the quick keys, so I can quickly jump between colors without having to use the dropdown. It just seemed more useful than last card in current color. Because I'm generally going to be taking 1 of 3 actions: next unfinished card, next card, next color, and sometimes prev versions of those options. I don't know why I'd ever want or need to jump to the card of the color I'm in. That's my thought anyway.

**Pull request merged**
