### PR TITLE
navigating between cards and colors should show load the correct card

### PR DESCRIPTION
**Pull request by LethargicDeveloper**

### CODE REVIEW

**Comment by deklinez** [comment]
This works fine but I don't really understand the fix.  Was the issue that without the `this.loading` changes it wasn't "waiting" for the right image or something?

**Review by deklinez — APPROVED** [review]

**Comment by LethargicDeveloper** [comment]
> This works fine but I don't really understand the fix. Was the issue that without the `this.loading` changes it wasn't "waiting" for the right card or something?

This only happens when navigating between colors. When you navigate between colors it loads the next (or prev) card, but it also sets the selected color dropdown to the new color, which was causing the onchange to trigger which loads the first card of that color. You would never notice when hitting next, because you'd be on the first card of the color anyway. But when hitting prev it would load the first card of the prev color.

The loading flag causes the color onchange to not try to load the first card.

**Comment by LethargicDeveloper** [comment]
I told you the code was garbage and convoluted :)

**Comment by deklinez** [comment]
Ahh right, I actually noticed that when looking into that bug but forgot all about it.

**Pull request merged**
